### ISSUE TITLE
Single line code block removed after conversion

### ISSUE THREAD

**Issue by kristijanhusak** [FooSoft/md2vim#3]
Hi,

I tried using this to convert some of my markdown docs to vimdoc, but I noticed that single line code blocks (the ones in single backtick) are completely removed after conversion.

Steps to reproduce:

Having this markdown file:
```markdown
## Title

Some text

`this is trimmed for some reason`
```

Running this command:
```
md2vim test.md test.txt
```

Produces this:

```vim
test.txt

================================================================================
CONTENTS                                                           *test-contents*

    1. Title..........................................................|test-title|

--------------------------------------------------------------------------------
TITLE                                                                 *test-title*

Some text




```

Is there a way to make it convert?

Edit:
Saw this comment: https://github.com/FooSoft/md2vim/blob/master/vimdoc.go#L323

I gave it a try manually, seems it's working fine, at least in latest Neovim.

**Comment by FooSoft** [comment]
Good catch, I verified that it does work properly now.
